import './globals.css';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang="jp">
    <body className={inter.className}>
      <div className="mx-auto min-h-screen max-w-md bg-white drop-shadow-2xl">{children}</div>
    </body>
  </html>
);

export default RootLayout;
